source: src
paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
  layouts:
collections_config:
  pages:
    path: pages
    output: true
    url: dist/pages
    filter:
    parse_branch_index:
    name: Pages
    description: ''
    icon: description
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - content
      - visual
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: Etc/UTC
