source: src
paths:
  uploads: assets/uploads/:title
  static: ''
  collections: ''
  data: _data
  layouts: _includes
  includes: _includes
data_config:
  fonts: true
  authors: true
  blogTags: true
collections_config:
  data:
    path: _data
    output: false
    icon: settings
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    url: dist/pages
    filter:
      exclude:
        - robots.njk
        - rss.njk
        - sitemap.njk
        - tags.md
        - pages.json
    parse_branch_index: null
    name: Pages
    description: All your pages
    icon: description
    documentation: null
    preview:
      gallery: description
    sort: null
    sort_options: null
    singular_name: null
    singular_key: null
    _editables: null
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      eleventyExcludeFromCollections:
        type: switch
        label: Remove from navigation
        comment: Will remove this page from top navigation top nav and footer
      eleventyNavigation:
        label: Navigation
      eleventyNavigation.key:
        comment: How this page is identified in the navigation
      eleventyNavigation.order:
        comment: What order in the navigation
      eleventyNavigation.title:
        label: Display Title
        comment: >-
          What website visitors will see. Leave blank if you want to use the key
          as Display Title
      eleventyNavigation.parent:
        comment: What key this should be grouped with. Leave blank for no grouping
      pageLink:
        label: Page Location
        comment: The location of this page on your webiste i.e. Example.com/mylocation
        type: text
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      permalink:
        hidden: true
      pagination:
        hidden: true
      layout:
        hidden: true
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    schema_key: null
  blog:
    path: posts
    output: true
    url: dist/blog
    filter:
      exclude:
        - posts.json
    '-enabled_editors':
      - content
      - visual
    _inputs:
      title:
        label: Page Title
        comment: Seo focused page title
      metaDesc:
        type: textarea
        label: Meta Description
        comment: SEO focused page summary
      author:
        type: select
        options:
          values: data.authors
          value_key: id
          text_key: name
      tags:
        type: multiselect
        options:
          values: data.blogTags
      date:
        label: Published Date
        _instance_value: NOW
      image:
        hidden: true
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
_inputs:
  blogCards:
    type: object
    options:
      structures: _structures.blog_cards
  hero:
    type: object
    options:
      structures: _structures.hero_blocks
  description:
    type: markdown
    options:
      link: true
      bold: true
      italic: true
      undo: true
      redo: true
      initial_height: 135
  color_group:
    type: select
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values:
        - id: primary
          name: Primary
        - name: Magic
          id: magic0
        - name: Rose
          id: rose1
        - name: Cotton Candy
          id: cotton_candy2
        - name: Orange
          id: orange3
        - name: PurpleNurple
          id: purplenurple4
  id:
    hidden: true
    _instance_value: UUID
  arrangement:
    type: select
    comment: The layout of the icon and text together
    options:
      values:
        - name: Inline
          id: inline
        - name: Stacked
          id: stacked
  sectionId:
    comment: >-
      An ID given to a section to be able to link to it Example:
      example.com/#sectionId where sectionID is what you type in this box
  font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  heading_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  content_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
  logo_font:
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here. Note: fonts needs to have at least style 400 and 700
      available
    type: select
    options:
      values: data.fonts
_select_data: {}
_structures:
  content_blocks:
    style: modal
_editables: {}
timezone: Etc/UTC
