source: src
paths:
  uploads: "assets/uploads/:title"
  static: ""
  collections: ""
  data: _data
  layouts: _includes
  includes: _includes

_structures:
  content_blocks:
    style: modal

collections_config:
  data:
    path: _data
    output: false
    icon: insert_chart_outline
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    url: dist/pages
    filter:
      exclude:
        - robots.njk
        - rss.njk
        - sitemap.njk
        - tags.md
        - pages.json
    parse_branch_index:
    name: Pages
    description: "All your pages"
    icon: description
    documentation:
    preview:
      gallery: description
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: "Page Title"
        comment: "Seo focused page title"
      eleventyExcludeFromCollections:
        type: "switch"
        label: "Remove from navigation"
        comment: "Will remove this page from top navigation top nav and footer"
      eleventyNavigation:
        label: "Navigation"
      eleventyNavigation.key:
        comment: "How this page is identified in the navigation"
      eleventyNavigation.order:
        comment: "What order in the navigation"
      eleventyNavigation.title:
        label: "Display Title"
        comment: "What website visitors will see. Leave blank if you want to use the key as Display Title"
      eleventyNavigation.parent:
        comment: "What key this should be grouped with. Leave blank for no grouping"
      pageLink:
        label: "Page Location"
        comment: "The location of this page on your webiste i.e. Example.com/mylocation"
        type: "text"
      metaDesc:
        type: "textarea"
        label: "Meta Description"
        comment: "SEO focused page summary"
      permalink:
        hidden: true
      layout:
        hidden: true
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    schema_key:
_inputs:
  heading_font:
    type: select
    options:
      values: data.fonts
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here
  content_font:
    type: select
    options:
      values: data.fonts
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here
  logo_font:
    type: select
    options:
      values: data.fonts
    comment: >-
      Write the name of any font from
      [https://fonts.google.com/](https://fonts.google.com/) in data/fonts to
      access it here
data_config:
  fonts: true
_select_data: {}
_editables: {}
timezone: Etc/UTC
