source: src
paths:
  uploads: "uploads/:title"
  static: ""
  collections: ""
  data: ""
  layouts:
collections_config:
  pages:
    path: pages
    output: true
    url: dist/pages
    filter:
      exclude:
      - robots.njk
      - rss.html
      - sitemap.njk
      - tags.md
      - pages.json
    parse_branch_index:
    name: Pages
    description: "All your pages"
    icon: description
    documentation:
    preview: 
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - content
      - visual
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: Etc/UTC
