source: src
paths:
  uploads: "uploads/:title"
  static: ""
  collections: ""
  data: ""
  layouts:
collections_config:
  pages:
    path: pages
    output: true
    url: dist/pages
    filter:
      exclude:
      - robots.njk
      - rss.html
      - sitemap.njk
      - tags.md
      - pages.json
    parse_branch_index:
    name: Pages
    description: "All your pages"
    icon: description
    documentation:
    preview: 
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        label: "Page Title"
      eleventyExcludeFromCollections:
        type: "switch"
        label: "Remove from navigation"
        comment: "Will remove this page from top navigation top nav and footer"
      eleventyNavigation:
        label: "Navigation"
        key:
          comment: "How this page is identified in the navigation"
        order:
          comment: "What order in the navigation"
        title:
          label: "Display Title"
          comment: "What website visitors will see. Leave blank if you want to use the key as Display Title"
        parent:
          comment: "What key this should be grouped with. Leave blank for no grouping"
      pageLink:
        label: "Page Location"
        comment: "The location of this page on your webiste i.e. Example.com/mylocation"
        type: "text"
      permalink:
        hidden: true
      layout:
        hidden: true
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    new_preview_url:
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    schema_key:
timezone: Etc/UTC
