# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image Gallery Masonry Grid"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    showNote: true
    heading: bookshop:generic/heading!
    imageSets:
      - images: [bookshop:generic/imageModal]
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  imageSets:
    comment: "Each image set can have up to 8 images. Any image added past the eith will not show up"