# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Blog Cards Partial"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  contents:
    heading: bookshop:generic/heading!
    randomize: false
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
