# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Full Image Hero"
  description: Provide concise information at the top of the page to engage website visitors
  icon: feed
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    highlightEybrow: false
    eyebrow:
    headline:
    description: "Hello World!"
    buttons: [bookshop:generic/button]
    image: bookshop:generic/image!
  styles:
    color_group: primary
    contentAlignment: left
    backgroundOpacity: '50'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  styles:
    contentAlignment: left
    color_group: primary
  content:
    highlightEybrow: true
    eyebrow: eybrow
    headline: headline
    button:
      url: "#"
      text: "Button text"
      color_group: primary
    description: "Hello World!"
    image:
      _bookshop_name: generic/image
      imagePath: /images/tree.jpg
      imageAlt: Tree in the middle of a field with the sunsetting on the left

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  contentAlignment:
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Left
          id: left
          icon: format_align_left
        - name: Center
          id: center
          icon: format_align_center
        - name: Right
          id: right
          icon: format_align_right
  backgroundOpacity:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - name: '0%'
          id: '0'
        - name: '5%'
          id: '5'
        - name: '10%'
          id: '10'
        - name: '20%'
          id: '20'
        - name: '25%'
          id: '25'
        - name: '30%'
          id: '30'
        - name: '40%'
          id: '40'
        - name: '50%'
          id: '50'
        - name: '60%'
          id: '60'
        - name: '70%'
          id: '70'
        - name: '80%'
          id: '80'
        - name: '90%'
          id: '90'
        - name: '95%'
          id: '95'
        - name: '100%'
          id: '100'
