# Metadata about this component, to be used in the CMS
spec:
  structures:
    - card_imagery_blocks
    - icon_blocks
    - content_blocks
  label: "Hero Library Icon"
  description: An icon (from https://heroicons.com/) with an optional border and customisable color
  icon: bolt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heroLibraryIconName: academic-cap
  iconSize: small
  iconType: solid
  roundedBorder: false
  themeColor: false
  color: "#7d7f7c"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  theme_color:
    comment: Use your theme color for the icon color and the rounded border color (if one is included)
    type: checkbox
  icon_size:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Small
          id: small
        - name: Large
          id: large
        - name: Micro
          id: micro
  icon_type:
    comment: >-
      Choose outline if you want lines to be filled with color and solid if you
      want the whole image filled with color
    type: choice
    options:
      allow_empty: false
      values:
        - name: Solid
          id: solid
        - name: Outline
          id: outline