# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "ImageGallery"
  description:
  icon: space_dashboard
  tags: []

# Make it so that the image set isn't an array of images but is just a single array.
# Recreate it correctly and ymlify it back into the grid component
# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:generic/heading!
    imageSets:
      - images: [bookshop:generic/image]
    buttons: [bookshop:generic/button]
    setLimit: 999
    patternLimit: 1
    imageClasses:
    - "" # This will always be empty and is needed for the grid to work
    - ""
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  imageSets:
    comment: "Each image set can have up to 8 images. Any image added past the eith will not show up"
  imageClasses:
    hidden: true
  setLimit:
    hidden: true
  patternLimit:
    hidden: true
