# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Pricin gCard"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: Pricing Card
    shortDescription:
    price: $0
    priceDescription:
    description:
  styles:
    card_color_group: primary
    highlight: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  shortDescription:
    comment: A short description of the service. Example "Perfect for beginners"
