# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Pricing Card"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: Pricing Card
    shortDescription:
    price: $0
    priceDescription:
    description:
  styles:
    card_color_group: primary
    highlight: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  shortDescription:
    comment: A short description of the service. Example "Perfect for beginners"
  priceDescription:
    comment: A description of the price. Examples "Paid monthly" or "Paid upfront"
  description:
    type: markdown
    options:
      link: true
      blockquote: false
      bold: true
      format: p h3 h4 h5 h6
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      numberedlist: true
      indent: false
      outdent: false
      code: false
      embed: false
      horizontalrule: false
      image: false
      table: false
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      snippet: false
