# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Entry"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    entries:
      - entry:
          heading: bookshop:generic/heading!
          image: bookshop:generic/image!
          id:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
