# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image Compare"
  description:
  icon: compare
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    showNote: true
    heading: bookshop:generic/heading!
    leftImage: bookshop:generic/image!
    rightImage: bookshop:generic/image!
  styles:
    color_group: primary


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
